//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Video Analyse Configuration.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_VIDEOANALYSECONFIGURATION_DIALOG 102
#define IDD_CONFIG_TRAFFICSCENE         103
#define IDD_CONFIG_MODULE               104
#define IDD_CONFIG_RULES                105
#define IDD_CONFIG_TRAFFICGATE          106
#define IDD_SCENESHOW_DIALOG            107
#define IDR_MAINFRAME                   128
#define IDD_PICTURE_SHOW                129
#define IDD_COFNIG_CROSSLINE_RULE       132
#define IDD_COFNIG_FACEDETECT_RULE      133
#define IDD_CONFIG_CROSSREGION_RULE     134
#define IDD_CONFIG_WANDER_RULE          135
#define IDD_CONFIG_RIOTER_RULE          136
#define IDD_CONFIG_PASTE_RULE           137
#define IDD_CONFIG_ATM_SCENE            138
#define IDD_CONFIG_FACE_SCENE           139
#define IDC_EDIT_RULENAME_TG            1000
#define IDC_EDIT_OBJTYPE_M              1002
#define IDC_EDIT_CAMERAH_T              1003
#define IDC_EDIT19                      1004
#define IDC_BUTTON_SAVE_R               1004
#define IDC_EDIT_METRICDIS              1004
#define IDC_EDIT_MINSY_M                1005
#define IDC_BUTTON_LOGOUT               1005
#define IDC_EDIT_OBJMAXSX_M             1006
#define IDC_TAB_ATTRIBUTE               1006
#define IDC_EDIT_MAXSX_M                1006
#define IDC_COMBO_CHANNEL_M             1007
#define IDC_COMBO_MODULES_M             1008
#define IDC_EDIT_MAXSY_M                1009
#define IDC_EDIT_NDPY_T                 1010
#define IDC_EDIT_MINSA_M                1010
#define IDC_EDIT_NDPTCD_T               1011
#define IDC_EDIT_MAXSA_M                1011
#define IDC_EDIT_FDPX_T                 1012
#define IDC_BUTTON_SAVE_M               1012
#define IDC_EDIT_FDPY_T                 1013
#define IDC_BUTTON_REFRESH_M            1013
#define IDC_EDIT_FDPTCD_T               1014
#define IDC_CHECK_SNAP_M                1017
#define IDC_COMBO_FILTERTYPE_M          1021
#define IDC_LIST_OBJTYPE_TG             1036
#define IDC_EDIT_IP                     1037
#define IDC_LIST_OBJTYPE_TG2            1037
#define IDC_EDIT_PORT                   1038
#define IDC_EDIT_USERNAME               1039
#define IDC_EDIT_PASSWORD               1040
#define IDC_BUTTON_LOGIN                1041
#define IDC_CHECK_ENABLE_TG             1042
#define IDC_EDIT_CARWAYID_TG            1043
#define IDC_EDIT_SPEEDWGT_TG            1044
#define IDC_EDIT_SPEEDUL_TG             1045
#define IDC_EDIT_SPEEDLL_TG             1046
#define IDC_COMBO_CHANNEL_T             1047
#define IDC_EDIT_CAMERAD_T              1049
#define IDC_EDIT_NDPX_T                 1050
#define IDC_BUTTON_SAVE_T               1052
#define IDC_BUTTON_REFRESH_T            1053
#define IDC_COMBO_CHANNEL_R             1054
#define IDC_TAB_RULES                   1055
#define IDC_STATIC_VEDIO                1056
#define IDC_EDIT_OBJMINSX_M             1057
#define IDC_EDIT_MINSX_M                1057
#define IDC_BUTTON_ADDRULE_R            1057
#define IDC_COMBO_SCENE_T               1058
#define IDC_BUTTON_DELETRULE_R          1058
#define IDC_COMBO_OBJTYPE               1059
#define IDC_BUTTON_ADDMOD               1060
#define IDC_BUTTON_DELETSELMOD          1061
#define IDC_BUTTON_REPAINT_CW           1063
#define IDC_RADIO_DETECT                1066
#define IDC_BUTTON_REFRESH_R            1067
#define IDC_MY_CROSS                    1069
#define IDC_TREE1                       1069
#define IDC_TREE_MODULE                 1069
#define IDC_BUTTON_SET_DETECTREGION     1070
#define IDC_LIST_ROAD                   1073
#define IDC_BUTTON_ADDROAD              1074
#define IDC_BUTTON_DELETROAD            1075
#define IDC_BUTTON_CHANGEROAD           1078
#define IDC_EDIT_ROADID                 1078
#define IDC_COMBO_DIRECTION             1079
#define IDC_STATIC_ROADID               1080
#define IDC_STATIC_DIRECTION            1081
#define IDC_STATIC_SHOW                 1082
#define IDC_RADIO1                      1083
#define IDC_RADIO2                      1084
#define IDC_RADIO3                      1085
#define IDC_RADIO4                      1086
#define IDC_RADIO5                      1087
#define IDC_BUTTON_REPAINT              1088
#define IDC_TREE_RULES                  1090
#define IDC_BUTTON_SET                  1091
#define IDC_BUTTON_SET_RULELINES_TG     1091
#define IDC_EDIT_RULENAME               1092
#define IDC_COMBO_DIRECT                1095
#define IDC_STATIC_TriggerPosition      1096
#define IDC_COMBO2                      1097
#define IDC_COMBO_ACTIONTYPE_TG         1098
#define IDC_EDIT_MinTargets             1099
#define IDC_EDIT_MaxTargets             1100
#define IDC_EDIT_MinDuration            1101
#define IDC_EDIT_ReportInterval         1102
#define IDC_EDIT_TriggerTargetsNumber   1103
#define IDC_COMBO_TriggerPosition       1104
#define IDC_EDIT_AreaPercent            1105
#define IDC_EDIT_CameraHeight           1107
#define IDC_EDIT_CameraDistance         1108
#define IDC_EDIT_MainDirection          1109
#define IDC_EDIT_FaceAngleDown          1110
#define IDC_EDIT_FaceAngleUp            1111
#define IDC_EDIT_FaceAngleLeft          1112
#define IDC_EDIT_FaceAngleRight         1113
#define IDC_STATIC1                     1114

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1115
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
