#ifndef MESSAGETEXT_H
#define MESSAGETEXT_H

#include <windows.h>

#define MSG_ERROR_PASSWORD			"Incorrect Password"
#define MSG_ERROR_USER				"User not Exist"
#define MSG_ERROR_TIMEOUT			"Login Timeout"
#define MSG_ERROR_RELOGGIN			"Curent User Has Logined"
#define MSG_ERROR_LOCKED			"Curent User Locked"
#define MSG_ERROR_BLACKLIST			"Curent User Invalid"
#define MSG_ERROR_BUSY				"System Busy"
#define MSG_ERROR_CONNECT			"Cant find host"
#define MSG_ERROR_MAXCONNECT		"MaxConncet"
#define MSG_ERROR_PROTOCOL3_ONLY	"Protocol 3 Only"
#define MSG_ERROR_UKEY_LOST			"UKey Lost"
#define MSG_ERROR_ERROR_NO_AUTHORIZED		"No Authorized"
#define MSG_ERROR_NETWORK			"Network Error"
#define MSG_ERROR_LISTEN			"Start Listen Error"
#define MSG_DEVICE_DISCONNECT		"device disconnect"

#define MSG_ERROR_IOCTRL_IN			"Set Alarm Input Error"
#define MSG_ERROR_IOCTRL_OUT		"Set Alarm Output Error"
#define MSG_ERROR_ALARMCHL_OVERMAX	"Input Alarm in Counter Error"
#define MSG_ERROR_ALARM_STATUS		"Get Alarm Status Error"

#define MSG_CLIENTSTATE_DISKERR			"Bad Disk:"
#define MSG_CLIENTSTATE_ALARM			"Alarm:"
#define MSG_CLIENTSTATE_RECORDING		"Record:"
#define MSG_CLIENTSTATE_MOTION			"Motion Detect:"
#define MSG_CLIENTSTATE_VIDEOLOST		"Video Loss:"
#define MSG_CLIENTSTATE_CLIENTSTATE		"Client State:"
#define MSG_CLIENTSTATE_SOUND			"Sound Detect£º"
#define MSG_CLIENTSTATE_SHELTER			"Shelter Alarm"
#define MSG_CLIENTSTATE_DISKFULL		"Disk Full£º"
#define MSG_CLIENTSTATE_SERIAL			"Serial No:"
#define MSG_CLIENTSTATE_ALMDEC			"Alarm Decoder"
#define MSG_WORKSTATE_SHELTER			"Shelter Alarm:"
#define MSG_WORKSTATE_RECORDING			"Recording:"

#define MSG_WORKSTATE_CLIENTSTATE		"Device Status    :  "
#define MSG_WORKSTATE_NORMAL			"No error"
#define MSG_WORKSTATE_CPUTOOHIGH		"cpu Use out"
#define MSG_WORKSTATE_HARDWAREEROR		"Hardware Error"
#define MSG_WORKSTATE_UNKNOWNEEROR		"Unknown Error"
#define MSG_WORKSTATE_DISPLAYSTATE		"   Device display status: "
#define MSG_WORKSTATE_UNNORMAL			"Unnormal"
#define MSG_WORKSTATE_RECORDCHL			"Record Channel        :  "
#define MSG_WORKSTATE_VIDEOLOSTCHL		"Video Lost Channel:  "
#define MSG_WORKSTATE_HARDWAREERRCHL	"Hardware Error Channel:  "
#define MSG_WORKSTATE_VIDEOLOSTCHL		"Video Lost Channel:  "
#define MSG_WORKSTATE_ALARMINPUT		"Alarm Input:  "
#define MSG_WORKSTATE_ALARMOUTPUT		"Alarm Output:  "

#define MSG_PTZCTRL_NOCHANNEL			"No Channel Openned"
#define MSG_PTZCTRL_CTRLFAILED			"PTZ Control Failed"

#define MSG_DEMODLG_SPLITTYPE_1			"single"
#define MSG_DEMODLG_SPLITTYPE_4			"split-4"
#define MSG_DEMODLG_SPLITTYPE_9			"split-9"
#define MSG_DEMODLG_SPLITTYPE_16		"split-16"
#define MSG_DEMODLG_CHECKSEL			"No device selected"
#define MSG_DEMODLG_PLAYING				"Playing back net-file."
#define MSG_DEMODLG_OPENCHLFAILED		"Open channel failed"
#define MSG_DEMODLG_NOPREVIEW			"No Multi-Preview"
#define MSG_DEMODLG_SAVEDATAFAILED		"Save data failed"
#define MSG_DEMODLG_PLAYFAILED			"Open net-play failed"
#define MSG_DEMODLG_PTZCMDFAILED		"PTZ command failed, check the parameter"
#define MSG_DEMODLG_NOTOPENNED			"Screen closed"
#define MSG_DEMODLG_PTZCTRLFAILED		"PTZ control failed"
#define MSG_DEMODLG_NOTPLAYING			"Not playing"
#define MSG_DEMODLG_PLAYCTRLFAILED		"Playing control failed"
#define MSG_DEMODLG_PAUSE				"  Pauze  "
#define MSG_DEMODLG_PLAY				"  Play  "
#define MSG_DEMODLG_STOPPLAYFAILED		"Stop playing failed"
#define MSG_DEMODLG_CANTCAPTURE			"Screen closed. Cannot capture"
#define MSG_DEMODLG_CAPTUREFAILED		"Capture failed"
#define MSG_DEMODLG_CANTFORCE_I			"Cannot compel I frame"
#define MSG_DEMODLG_FAILEDFORCE_I		"Compel I frame failed"
#define MSG_DEMODLG_REALSAVE_STOPPED	"Saving real data  stopped"
#define MSG_DEMODLG_MONITOR				"Monitor"
#define MSG_DEMODLG_PREVIEW				"Preview"
#define MSG_DEMODLG_PLAYBACKCHL			"Play back channel"
#define MSG_DEMODLG_CYCLEMONITOR		"Cycle Monitor"
#define MSG_DEMODLG_UPDATING			"Upgrading...."
#define MSG_DEMODLG_UPDATEFAILED		"Upgrade failed"
#define MSG_DEMODLG_NOTMONITOR			"No monitor screen selected"
#define MSG_DEMODLG_OPENTALKFAILED		"Open talk-channel failed"
#define MSG_DEMODLG_CLOSETALKFAILED		"Close talk-channel failed"
#define MSG_DEMODLG_OPENFILEFAILED		"Canceled"
#define MSG_DEMODLG_ERROR_CYCLING		"Current channel is within cycle monitor list!"
#define MSG_DEMODLG_REBOOTFAILED		"Reboot device failed"
#define MSG_DEMODLG_REBOOTDONE			"Reboot done"
#define MSG_DEMODLG_SHUTDOWNFAILED		"Shut down device failed"
#define MSG_DEMODLG_SHUTDOWNDONE		"Shut down done"

#define MSG_RECORDCTRL_SETUPFAILED		"Setup recording config failed"
#define MSG_RECORDCTRL_QUERYSTATEFAILED	"Query record status failed"

#define MSG_SCHRECORD_NODEVICE			"No device selected"
#define MSG_SCHRECORD_CHOOSEDEVICE		"Select device"
#define MSG_SCHRECORD_CHLNO_INVALID		"Channel number invalid"
#define MSG_SCHRECORD_CHLNO				"Channel Num"
#define MSG_SCHRECORD_TIMEINPUT_ERR		"Time input Erroe"
#define MSG_SCHRECORD_TIMEINPUT			"Time input"
#define MSG_SCHRECORD_QUERYFAILED		"Query failed"
#define MSG_SCHRECORD_NORECORD			"No record"
#define MSG_SCHRECORD_QUERYTYPE_LIST	"Query-list"
#define MSG_SCHRECORD_QUERYTYPE_ALARM	"Query-alarm"
#define MSG_SCHRECORD_QUERYTYPE_CARD	"Query-card"
#define MSG_SCHRECORD_DVC_AND_CHL		"Device and channel"
#define MSG_SCHRECORD_STARTTIME			"Start time"
#define MSG_SCHRECORD_ENDTIME			"End time"
#define MSG_SCHRECORD_SIZE				"Size"
#define MSG_SCHRECORD_DOWNLORD_CB_ERR	"Download callback failed"
#define MSG_SCHRECORD_DOWNLOAD_FIN		"Download complete"
#define MSG_SCHRECORD_DOWNLOADFILE_SEL	"Select file for download"
#define MSG_SCHRECORD_DOWNLOAD			"Start"
#define MSG_SCHRECORD_CANCELDOWNLOAD		"Stop"
#define MSG_SCHRECORD_CANCELED			"Download Stopped"
#define MSG_SCHRECORD_PLAYFILE_SEL		"Select file for playing"
#define MSG_SCHRECORD_PLAY				"Play"
#define MSG_SCHRECORD_STARTDLFAILED		"Start Download Failed!"
#define MSG_SCHRECORD_STOPDLFAILED		"Stop Download Failed!"
#define MSG_SCHRECORD_ILLEGALFRAME		"Illegal framerate!"

#define MSG_SPLITINFO_BLANK				"Blank"
#define MSG_SPLITINFO_MONITOR			"Monitor"
#define MSG_SPLITINFO_PLAYBACK			"Net-play"
#define MSG_SPLITINFO_PREVIEW			"Preview"
#define MSG_SPLITINFO_CYCLEMONITOR		"Cyclemonitor"
#define MSG_SPLITINFO_NOLIMIT			" No limit "
#define MSG_SPLITINFO_NODEVICE			"Select device first"
#define MSG_SPLITINFO_CHOOSEDEVICE		"Select device"
#define MSG_SPLITINFO_LIMIT_FAILED		"Limiting rate failed"

#define MSG_TRANSCOM_DATABIT_BITS		"bit"
#define MSG_TRANSCOM_STOPBIT_1BIT		" 1 bit"
#define MSG_TRANSCOM_STOPBIT_15BITS		" 1.5 bits"
#define MSG_TRANSCOM_STOPBIT_2BITS		" 2 bits"
#define MSG_TRANSCOM_PARITY_NO			"No parity"
#define MSG_TRANSCOM_PARITY_ODD			"Odd parity"
#define MSG_TRANSCOM_PARITY_EVEN		"Even parity"
#define MSG_TRANSCOM_CLOSECOM			"Close com"
#define MSG_TRANSCOM_OPENCOM			"Open com"
#define MSG_TRANSCOM_OPENTRANSCOMFAILED	"Open com failed"
#define MSG_TRANSCOM_SENDDATAFAILED		"Send data failed"
#define MSG_TRANSCOM_SENDDATA_ERROR		"Data format error."
#define MSG_TRANSCOM_QUERYCOMPARAMFAILED	"Query com param failed"

#define MSG_CYCLE_OPENCHANNELFAILED		"Open channel failed while cycle monitoring"
#define MSG_CYCLE_CLOSECHANNELFAILED		"Open channel failed while cycle monitoring"
#define MSG_CYCLE_STOPCYCLEERROR		"Stop cycle monitor error!"
#define MSG_CYCLE_STOPMONITORERROR		"Stop monitor error!"
#define MSG_CYCLE_STOPNETPLAYERROR		"Stop net playback error!"
#define MSG_CYCLE_STOPMULTIPLAYERROR		"Stop Multiplay error!"

#define NAME_DEVICE				"Device"
#define NAME_CHANNEL				"Channel"
#define NAME_SCRN				"Scrn"
#define NAME_UNBROADCASTDEV		"UnBroadcast Dev"
#define NAME_BROADCASTDEV		"Broadcast Dev"

#define NAME_CFG_SERVERCONFIG			"Device"
#define NAME_CFG_CHANNELCONFIG			"Channel"
#define NAME_CFG_SERIALCONFIG			"Serial com"
#define NAME_CFG_ALARMCONFIG			"Alarm"
#define NAME_CFG_ALARMRECORD			"Record"
#define NAME_CFG_USERCONFIG				"User"
#define NAME_CFG_NETWORK				"Network"
/*
#define NAME_ALARMCFG_ALLINPUT			"All input"
#define NAME_ALARMCFG_INPUT			"Input"
#define NAME_ALARMCFG_ALLOUTPUT			"All output"
#define NAME_ALARMCFG_OUTPUT			"Output"
#define MSG_ALARMCFG_GETINPUTCFGFAILED		"Get alarm-input config failed"
#define MSG_ALARMCFG_GETOUTPUTCFGFAILED		"Get alarm-output config failed"
#define MSG_ALARMCFG_HOURERROR			"Hour range error"
#define MSG_ALARMCFG_MINUTEERROR		"Minute range error"
#define MSG_ALARMCFG_TIMEILLEGAL		"Timing length exceed 24:00"
#define MSG_ALARMCFG_TIMEILLEGAL2		"Timing illegal"
#define MSG_ALARMCFG_TIMEILLEGAL3		"timing illegal"
*/
#define NAME_CHANNELCFG_ALLCHANNEL		"All channel"
#define NAME_CHANNELCFG_CHANNEL			"Channel"
#define NAME_CHANNELCFG_STOPREC			"Stop recording"
#define NAME_CHANNELCFG_STARTREC		"Remote record"
#define MSG_CHANNELCFG_GETCHANNELCFGFAILED	"Get config failed! Channel:"

#define NAME_SERIALCFG_ALLCHANNEL		"All channel"
#define NAME_SERIALCFG_CHANNEL			"Channel"
#define MSG_SERIALCFG_PSWCHECKERROR		"PSW check error"


#define MSG_SERIALCFG_NONE			"No Parity"
#define MSG_SERIALCFG_ODD			"Odd Parity"
#define MSG_SERIALCFG_EVEN			"Even Parity"

#define MSG_CLOSESOUNDFAILED			"Failed to open sound"
#define MSG_OPENSOUNDFAILED				"Failed to close sound"

#define MSG_VERSION						"  --NetSDK Version:"

#define MSG_UG_OPENFILE				"Open file"
#define MSG_UG_FAILED				"failed"
#define MSG_UG_ERROR				"Error"
#define MSG_FILE_MISSTYPE				"Not BIOS Upgrade file!"
#define MSG_UG_STARTFAILED			"Start Upgrade Failed"
#define MSG_UG_SENDFAILED				"Send upgrade Failed"
#define MSG_UG_STOPFAILED				"StopUpgrade Failed"
#define MSG_UG_DONE				"Upgrade done. Device rebooting"
#define MSG_TRANSFER_DONE				"All files transfered, please wait..."
#define MSG_UP_PROGRESS					"Upgrade progress"

#define NAME_BTN_NORMAL					"Normal"
#define NAME_BTN_ADVANCE				"Advance"
#define NAME_BTN_PTZ					"PTZ"
#define NAME_BTN_DEVLIST				"DevList"
#define NAME_BTN_COLOR					"Color"
#define NAME_BTN_CBDATA					"CBData"
#define NAME_BTN_PBCTRL					"PBCtrl"

#define NAME_RUNTIME_CHANNEL			"Channel:"
#define NAME_RUNTIME_TOTAL				"Total:"

#define ERROR_NET_NOERROR					"No error"		
#define ERROR_NET_ERROR						"Unknown error"		
#define ERROR_NET_SYSTEM_ERROR				"Windows system error"
#define ERROR_NET_NETWORK_ERROR				"Network error, probably because of network-time-out"		
#define ERROR_NET_DEV_VER_NOMATCH			"No match protocol"		
#define ERROR_NET_INVALID_HANDLE			"Invalid handle"		
#define ERROR_NET_OPEN_CHANNEL_ERROR		"Failed to open channel"		
#define ERROR_NET_CLOSE_CHANNEL_ERROR		"Failed to close channel"		
#define ERROR_NET_ILLEGAL_PARAM				"Illegal parameter"		
#define ERROR_NET_SDK_INIT_ERROR			"Failed to initialize SDK"		
#define ERROR_NET_SDK_UNINIT_ERROR			"Failed to uninitialize SDK"		
#define ERROR_NET_RENDER_OPEN_ERROR			"Failed to open render"		
#define ERROR_NET_DEC_OPEN_ERROR			"Failed to open decoder"
#define ERROR_NET_DEC_CLOSE_ERROR			"Failed to close decoder"
#define ERROR_NET_MULTIPLAY_NOCHANNEL		"Channel number is zero"	
#define ERROR_NET_TALK_INIT_ERROR			"Failed to initialize Recoder"	
#define ERROR_NET_TALK_NOT_INIT				"Recorder is not initialized"			
#define ERROR_NET_TALK_SENDDATA_ERROR		"Error while sending audio data"
#define ERROR_NET_NO_TALK_CHANNEL			"No talking channel found"
#define ERROR_NET_NO_AUDIO					"Audio not openned"								
#define ERROR_NET_REAL_ALREADY_SAVING		"Already saving real data"		
#define ERROR_NET_NOT_SAVING				"Not saving real data"
#define ERROR_NET_OPEN_FILE_ERROR			"Failed to open file"
#define ERROR_NET_PTZ_SET_TIMER_ERROR		"Failed to active PTZ timer"		
#define ERROR_NET_RETURN_DATA_ERROR			"Unexpected data received"	
#define ERROR_NET_INSUFFICIENT_BUFFER		"Insufficient buffer"		
#define ERROR_NET_NOT_SUPPORTED				"Not supported"		
#define ERROR_NET_NO_RECORD_FOUND			"No record found"
#define ERROR_NET_LOGIN_ERROR_PASSWORD		"Incorrect password"
#define ERROR_NET_LOGIN_ERROR_USER			"User not Exist"	
#define ERROR_NET_LOGIN_ERROR_TIMEOUT		"Login Timeout"		
#define ERROR_NET_LOGIN_ERROR_RELOGGIN		"Curent User Has Logined"		
#define ERROR_NET_LOGIN_ERROR_LOCKED		"Curent User is Locked"		
#define ERROR_NET_LOGIN_ERROR_BLACKLIST		"Curent User is in blacklist"		
#define ERROR_NET_LOGIN_ERROR_BUSY			"System Busying"		
#define ERROR_NET_LOGIN_ERROR_CONNECT		"Connect Error"		
#define ERROR_NET_LOGIN_ERROR_NETWORK		"Network Error"	
#define ERROR_NET_LOGIN_ERROR_MAXCONNECT	"MaxConnect Error"
#define ERROR_NET_LOGIN_ERROR_PROTOCOL3_ONLY "Protocol 3 Only"									
#define ERROR_NET_RENDER_SOUND_ON_ERROR		"Render error: open audio"		
#define ERROR_NET_RENDER_SOUND_OFF_ERROR	"Render error: close audio"		
#define ERROR_NET_RENDER_SET_VOLUME_ERROR	"Render error: set volume"		
#define ERROR_NET_RENDER_ADJUST_ERROR		"Render error: set image parameter"		
#define ERROR_NET_RENDER_PAUSE_ERROR		"Render error: pause play"
#define ERROR_NET_RENDER_SNAP_ERROR			"Render error: snap picture"
#define ERROR_NET_RENDER_STEP_ERROR			"Render error: step"
#define ERROR_NET_RENDER_FRAMERATE_ERROR	"Render error: set framerate"		
#define ERROR_NET_CONFIG_DEVBUSY			"Device is busy"
#define ERROR_NET_CONFIG_DATAILLEGAL		"Illegal config data"
#define ERROR_NET_NO_INIT					"The SDK is not initialized"		
#define ERROR_NET_DOWNLOAD_END				"Download ended"

#define NAME_MENU_FULLSCREEN				"FullScreen"
#define NAME_MENU_MULTISCREEN				"MultiScreen"
#define NAME_MENU_AUTOADJUST				"AutoAdjust"

#define MSG_ALARMCFG_ALARMIN				"AlarmIn"
#define MSG_ALARMCFG_MOTION					"Motion"
#define MSG_ALARMCFG_VIDEOLOST				"VideoLost"
#define MSG_ALARMCFG_BLINE					"Blind"
#define MSG_ALARMCFG_DISK					"DiskAlarm"

#define MSG_ALARMCFG_WHOLEWEEK				"Whole week"
#define MSG_ALARMCFG_MONDAY					"Monday"
#define MSG_ALARMCFG_TUESDAY				"Tuesday"
#define MSG_ALARMCFG_WEDNESDAY				"Wedensday"
#define MSG_ALARMCFG_THURSDAY				"Thursday"
#define MSG_ALARMCFG_FRIDAY					"Friday"
#define MSG_ALARMCFG_SATURDAY				"Saturday"
#define MSG_ALARMCFG_SUNDAY					"Sunday"

#define NAME_ALARMCFG_NOPEN					"N_Open"
#define NAME_ALARMCFG_NCLOSE				"N-Close"

#define NAME_NETCFG_NET1					"10MBase-T"
#define NAME_NETCFG_NET2					"10MBase-T full-duplex"
#define NAME_NETCFG_NET3					"100MBase-TX"
#define NAME_NETCFG_NET4					"100M full-duplex"
#define NAME_NETCFG_NET5					"10M/100M Adapted"
#define NAME_NETCFG_REMOTE_ALARM			"Alarm server"
#define NAME_NETCFG_REMOTE_LOG				"Log server"
#define NAME_NETCFG_REMOTE_SMTP				"SMTP server"
#define NAME_NETCFG_REMOTE_MULTICAST		"Multi cast"
#define NAME_NETCFG_REMOTE_NFS				"NFS server"
#define NAME_NETCFG_REMOTE_FTP				"Ftp server"
#define NAME_NETCFG_REMOTE_PPPOE			"PPPoE server"
#define NAME_NETCFG_REMOTE_DDNS				"DDNS server"
#define NAME_NETCFG_REMOTE_DNS				"DNS server"

#define NAME_NETCFG_PPPOE_IP				"Regist IP"
#define NAME_NETCFG_DDNS_HOSTNAME			"DDNS host-name"

#define MSG_CONFIG_SUCCESS					"Apply successful"

#define NAME_STREAM_MAIN					"MainStream"
#define NAME_STREAM_SUB1					"SubStream_1"
#define NAME_STREAM_SUB2					"SubStream_2"
#define NAME_STREAM_SUB3					"SubStream_3"

#define PTZ_GET_STATE_ERR                   "Failed to get ptz location"

#endif
