#if !defined(AFX_SETDEVICECONFIG_H__A203B2DC_18AC_432B_BE27_7EC7D3169618__INCLUDED_)
#define AFX_SETDEVICECONFIG_H__A203B2DC_18AC_432B_BE27_7EC7D3169618__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CSetDeviceConfig wrapper class

class CSetDeviceConfig : public CWnd
{
protected:
	DECLARE_DYNCREATE(CSetDeviceConfig)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xaaa74029, 0x3456, 0x40ed, { 0xb7, 0xa5, 0xda, 0xbe, 0xe6, 0x36, 0xfb, 0x26 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	BOOL GetAutoScroll();
	void SetAutoScroll(BOOL bNewValue);
	BOOL GetAutoSize();
	void SetAutoSize(BOOL bNewValue);
	long GetAxBorderStyle();
	void SetAxBorderStyle(long nNewValue);
	long GetBorderWidth();
	void SetBorderWidth(long nNewValue);
	CString GetCaption();
	void SetCaption(LPCTSTR lpszNewValue);
	unsigned long GetColor();
	void SetColor(unsigned long newValue);
	COleFont GetFont();
	void SetFont(LPDISPATCH newValue);
	void SetRefFont(LPDISPATCH* newValue);
	BOOL GetKeyPreview();
	void SetKeyPreview(BOOL bNewValue);
	long GetPixelsPerInch();
	void SetPixelsPerInch(long nNewValue);
	long GetPrintScale();
	void SetPrintScale(long nNewValue);
	BOOL GetScaled();
	void SetScaled(BOOL bNewValue);
	void SetDeviceShowType(long* lpDeviceInfo);
	void SetDetectWinRGB(unsigned long unRed, unsigned long unGreen, unsigned long unBlue, unsigned long unType);
	void SendDeviceInfoData(long DeviceID, long lConfigType, long* lpReData, unsigned long ReDataLength);
	void CreateDeviceFram(unsigned long unLagType);
	void SetDetectAreaHandle(long SetDetectAreaHandle, unsigned long unDetectType);
	void SetConfigPageHide(long lPageIndex);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SETDEVICECONFIG_H__A203B2DC_18AC_432B_BE27_7EC7D3169618__INCLUDED_)
