//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Client_Demo.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CLIENT_DEMO_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_SERCH_DEVICE         129
#define IDD_DIALOG_FULLUP_SCREEN        130
#define IDR_MENU1                       131
#define IDD_DIALOG_ATTRIBUTE            132
#define IDD_DIALOG_SYSTEMMSG            133
#define IDD_DIALOG_SETTIME              134
#define IDD_DIALOG_DEVICE_USER          135
#define IDD_DIALOG_DEVICE_UPDATE        136
#define IDD_DIALOG_ENCODE               137
#define IDD_DIALOG_MAIN_STREAM          138
#define IDD_DIALOG_SECOND_STREAM        139
#define IDD_DIALOG_THIRD_STREAM         140
#define IDD_DIALOG_OSDSET               141
#define IDD_DIALOG_VIDEO_HIDE           142
#define IDD_DIALOG_HIDESCREEN           143
#define IDD_DIALOG_PICTURESET           144
#define IDD_DIALOG_INTERSET_AREA        145
#define IDD_DIALOG_INTERESTSCREEN       146
#define IDD_DIALOG_NET_PARAM            147
#define IDD_DIALOG_PPPOESET             148
#define IDD_DIALOG_DNS_SET              149
#define IDD_DIALOG_EMAIL_SET            150
#define IDD_DIALOG_UPNP_SET             151
#define IDD_DIALOG_FTP_SET              152
#define IDD_DIALOG_VIDEO_PLAN           153
#define IDD_DIALOG_VIDEO_TIME           154
#define IDD_DIALOG_HIDE_WARNING         155
#define IDD_DIALOG_HIDEALARM_SCREEN     156
#define IDD_DIALOG_MOVE_SENSE_SET       157
#define IDD_DIALOG_MOVESENSE_SCREEN     158
#define IDD_DIALOG_SERIAL_SET           159
#define IDD_DIALOG_CLOUD_SET            160
#define IDD_DIALOG_IOWARNING            161
#define IDD_DIALOG_WARNING_UPLOAD       162
#define IDD_DIALOG_GB28181_SET          163
#define IDD_DIALOG_VIDEO_PLAYBACK       164
#define IDD_DIALOG_LOST_WARNING         165
#define IDD_DIALOG_NET_DISK_SET         166
#define IDR_MENU2                       168
#define IDD_DIALOG_AVD_SET              169
#define IDD_DIALOG_NET_CONNECT_STATUS   170
#define IDD_DIALOG_JOINT_ACTION         171
#define IDD_DIALOG_SERACH_WIFI          172
#define IDD_DIALOG_DEVICE_STATE         173
#define IDD_DIALOG_CHANNEL_STREAM       174
#define IDD_DIALOG_SERACH_RECODE        176
#define IDD_DIALOG_CONNECT_WIFI         177
#define IDB_BITMAP_DEVICE_SUCCESS       178
#define IDB_BITMAP_DEVICE_FAIL          179
#define IDB_BITMAP_DEVICE_TREE          180
#define IDB_BITMAP1                     181
#define IDB_BITMAP_TREE                 182
#define IDB_BITMAP_CAMERA               183
#define IDB_BITMAP_LOGINFAIL            184
#define IDB_BITMAP_DRAG                 187
#define IDR_MENU3                       188
#define IDD_DIALOG_IRCUT_SET            189
#define IDR_MENU4                       192
#define IDD_DIALOG1                     193
#define IDD_DIALOG_NetWorkFaultCheck    196
#define IDD_DIALOG2                     197
#define IDD_DIALOG_BORDERDLG            197
#define IDD_DIALOG_PeaOsc               198
#define IDD_DIALOG_PeaOscScreen         199
#define IDD_DIALOG3                     200
#define IDB_BITMAP_SERVERC              201
#define IDB_BITMAP2                     203
#define IDB_BITMAP_SERVERFAIL           203
#define IDD_DIALOG_RECODESCREEN         204
#define IDD_DIALOG_HXHT                 205
#define IDD_PAGE_PEAOSC_SCREEN          206
#define IDD_DIALOG_HW_SET               208
#define IDD_DIALOG_CPC                  209
#define IDD_DIALOG_CPC_SCREEN           210
#define IDD_DIALOG_MESSAGE              212
#define IDD_DIALOG_PIR_ALARM            213
#define IDD_DIALOG4                     214
#define IDD_DIALOG_RTSPSERVER           214
#define IDD_DIALOG_HerdAnalyse          215
#define IDD_DIALOG_HerdAnalyseScreen    216
#define IDD_DIALOG_HERDTIME             217
#define IDD_DIALOG5                     218
#define IDD_DIALOG_ELEVATOR             218
#define IDD_DIALOG_ZTE                  219
#define IDC_TREE_MAIN                   1000
#define IDC_STATIC_TEXT                 1001
#define IDC_STATIC_MENU                 1002
#define IDC_STATIC_TIME                 1003
#define IDC_STATIC_SHOWTIME             1004
#define IDC_LIST_DEVICE                 1005
#define IDC_BUTTON_SERACHDEVICE         1006
#define IDC_STATIC_DECIVENAME           1007
#define IDC_EDIT_DEVICENAME             1008
#define IDC_STATIC_IP                   1009
#define IDC_EDIT_DEVICE_IP              1010
#define IDC_STATIC_PORT                 1011
#define IDC_EDIT_DEVICE_PORT            1012
#define IDC_STATIC_USERNAME             1013
#define IDC_EDIT_USER_NAME              1014
#define IDC_STATIC_USERPASSWORD         1015
#define IDC_EDIT_USER_PASSWORD          1016
#define IDC_STATIC_SCREEN               1017
#define IDC_STATIC_SCREENNUM            1018
#define IDC_COMBO_SCREEN_NUM            1020
#define IDC_BUTTON_SAVE                 1021
#define IDC_STATIC_SHOWVIDEO            1022
#define IDC_BUTTON_TALK                 1023
#define IDC_STATIC_GROUP                1024
#define IDC_BUTTON_ATTRIBUTE            1025
#define IDC_TREE_ATTRIBUTE              1026
#define IDC_STATIC_ATTRIBUTE            1027
#define IDC_EDIT_VENDER                 1030
#define IDC_STATIC1                     1031
#define IDC_EDIT_OUTTIME                1032
#define IDC_STATIC2                     1033
#define IDC_EDIT_VERSION                1034
#define IDC_STATIC3                     1035
#define IDC_STATIC4                     1036
#define IDC_STATIC5                     1037
#define IDC_STATIC6                     1038
#define IDC_STATIC7                     1039
#define IDC_STATIC8                     1040
#define IDC_STATIC9                     1041
#define IDC_STATIC10                    1042
#define IDC_EDIT_HARDWAREVERSION        1043
#define IDC_EDIT_INNUM                  1046
#define IDC_EDIT_OUTNUM                 1047
#define IDC_EDIT_CHANNELNUM             1048
#define IDC_EDIT_RS485                  1049
#define IDC_EDIT_RS232                  1050
#define IDC_COMBO_DEVICETYPE            1051
#define IDC_COMBO_MACHINETYPE           1052
#define IDC_EDIT_USER                   1052
#define IDC_EDIT_PASSWORD               1053
#define IDC_BUTTONFLASH                 1053
#define IDC_BUTTONSAVE                  1054
#define IDC_EDIT_NEWUSER                1054
#define IDC_EDIT_NEWPASSWORD            1055
#define IDC_BUTTON_FLASH                1056
#define IDC_CHECK_NTP                   1057
#define IDC_CHECKSUMMER                 1058
#define IDC_EDIT_IP                     1059
#define IDC_EDIT_TIME                   1060
#define IDC_EDIT_TIMEAREA               1063
#define IDC_BUTTON_OPENFILE             1064
#define IDC_EDIT_FILEPATH               1065
#define IDC_BUTTON_UPDATE               1066
#define IDC_COMBO_CHOOSE_CHANNEL        1068
#define IDC_CHECK_STARTVOICE            1069
#define IDC_COMBO_INVOICE               1070
#define IDC_EDIT_ZL                     1072
#define IDC_COMBO_ZS                    1073
#define IDC_EDIT_SPACEZ                 1074
#define IDC_TABSTREAM                   1074
#define IDC_COMBO_RESOLUTION            1075
#define IDC_COMBO_QUALITY               1076
#define IDC_EDIT_MLV                    1077
#define IDC_CHECK_IFFIRST               1078
#define IDC_COMBO_WLV                   1079
#define IDC_COMBO_CHANNEL               1079
#define IDC_COMBO_ENCODEORDER           1080
#define IDC_COMBO_CLOUDPROTOCOL         1080
#define IDC_COMBO_ENCODEMODEL           1081
#define IDC_STATIC_SHOWSCREEN           1081
#define IDC_COMBO_ADDRESSSTREAM         1081
#define IDC_CHECK_SHOWTIME              1082
#define IDC_CHECK_SHOWTEXT              1083
#define IDC_EDIT_TEXT                   1084
#define IDC_CHECK_SHOWTEXT2             1085
#define IDC_EDIT_TEXT2                  1086
#define IDC_CHECKSHOWSTREAM             1087
#define IDC_EDIT_TIMEY                  1088
#define IDC_EDIT_TEXTY                  1089
#define IDC_EDIT_TIMEX                  1090
#define IDC_EDIT_TEXTX                  1091
#define IDC_CHECK_STARTHIDE             1092
#define IDC_EDIT_TEXTY2                 1092
#define IDC_CHECK_STARTPAINT            1093
#define IDC_EDIT_TEXTX2                 1093
#define IDC_BUTTON_CLEAR                1094
#define IDC_CHECK_SHOWTEXT3             1094
#define IDC_EDIT_TEXT3                  1095
#define IDC_EDIT_TEXTY3                 1096
#define IDC_EDIT_TEXTX3                 1097
#define IDC_SLIDER_COMPARE              1098
#define IDC_SLIDER_SATURATION           1099
#define IDC_SLIDER_LIGHT                1100
#define IDC_SLIDER_GRAY                 1101
#define IDC_SLIDER_SHAR                 1102
#define IDC_CHECK_IMAGE                 1103
#define IDC_CHECK_ROLLTURN              1104
#define IDC_COMBO_FLICKER               1105
#define IDC_COMBO_WHITETYPE             1106
#define IDC_SLIDER_WHITE_RED            1107
#define IDC_SLIDER_WHITE_BLUE           1108
#define IDC_COMBOLIGHTTYE               1109
#define IDC_SLIDER_LIGHTMAKEUP          1110
#define IDC_COMBOAUTOLIGHT              1111
#define IDC_COMBO_OUTSPRAY              1112
#define IDC_COMBO_ROTE                  1113
#define IDC_SLIDER_JIBIANCHECK          1114
#define IDC_SLIDER_WIDTHSTATE           1115
#define IDC_CHECK_START                 1117
#define IDC_BUTTONCLEAR                 1118
#define IDC_COMBO_NETWORKCARDING        1120
#define IDC_EDIT_SIGNPORT               1121
#define IDC_EDIT_DATAPORT               1122
#define IDC_EDIT_WEBPORT                1123
#define IDC_COMBO_NETWORKTYPE           1124
#define IDC_EDIT_TALK_PORT              1124
#define IDC_EDIT_MACADDRESS             1125
#define IDC_EDIT_IPADDR                 1126
#define IDC_CHECK_STARTDHCP             1127
#define IDC_EDIT_CHILDNET               1128
#define IDC_EDIT_NETADDRESS             1129
#define IDC_CHECK_STARTAUTODNS          1130
#define IDC_EDIT_MAINDNS                1131
#define IDC_EDIT_BACKUPDNS              1132
#define IDC_EDIT_WEBPORT2               1133
#define IDC_EDIT_TALKPORT               1133
#define IDC_CHECKSTARTTERRACE           1135
#define IDC_COMBO_TRANSPROTOCOL         1136
#define IDC_EDIT_CMSADDR                1137
#define IDC_EDIT_CMSPORT                1138
#define IDC_CHECK_STARTPPPOE            1138
#define IDC_EDIT_MDSPORT                1139
#define IDC_EDIT_MDSADDR                1140
#define IDC_COMBO_USENETWORK            1140
#define IDC_EDIT_PUID                   1141
#define IDC_EDIT_DEVICEIP               1141
#define IDC_EDIT_USERNAME               1142
#define IDC_CHECK_STARTDDNS             1147
#define IDC_COMBO_DDNSTYPE              1148
#define IDC_COMBO_UPDATETIME            1150
#define IDC_EDIT_AREA                   1151
#define IDC_EDIT_PORT                   1152
#define IDC_CHECK_SSL                   1157
#define IDC_EDIT_SMTPSERVER             1158
#define IDC_EDIT_SMTPPORT               1159
#define IDC_EDIT_EMAILADDR              1160
#define IDC_EDIT_SMTPPASSWORD           1161
#define IDC_CHECK_STARTUPNP             1161
#define IDC_EDIT_SMTPUSER               1162
#define IDC_COMBO_SHINETYPE             1162
#define IDC_EDIT_EMAILRESIVE1           1163
#define IDC_EDIT_SERVERIP               1163
#define IDC_EDIT_EMAILRESIVE2           1164
#define IDC_COMBO_NETCARDSHINE          1164
#define IDC_EDIT_EmailResive3           1165
#define IDC_EDIT_DATA_PORT              1165
#define IDC_EDIT_CMD_PORT               1166
#define IDC_COMBO_DATAPORTSTATUS        1167
#define IDC_EDIT_DATA_STATUS            1167
#define IDC_COMBO_WENPORTSTATUS         1168
#define IDC_EDIT_WEB_STATUS             1168
#define IDC_COMBO_UPNPUPDATETIME        1169
#define IDC_COMBO_CMDPORTSTATUS         1170
#define IDC_EDIT_CMD_STATUS             1170
#define IDC_COMBO_WENPORTSTATUS2        1171
#define IDC_COMBO_TALKPORTSTATUS        1171
#define IDC_EDIT_DATA_STATUS4           1171
#define IDC_EDIT_TALK_STATUS            1171
#define IDC_EDIT_FTPIP                  1172
#define IDC_EDIT_FTPPATH                1173
#define IDC_EDITFTPPORT                 1174
#define IDC_EDIT_FTPUSER                1175
#define IDC_EDIT_FTPPASSWORD            1176
#define IDC_LIST_DISK                   1176
#define IDC_COMBO_STREAMTYPE            1177
#define IDC_EDIT_SECOND                 1178
#define IDC_CHECK_AUTOCOVER             1179
#define IDC_BUTTON_TIMESET              1180
#define IDC_COMBO_WEEK                  1181
#define IDC_CHECK_VIDEOTIME1            1184
#define IDC_CHECK_VIDEOTIME2            1185
#define IDC_CHECK_VIDEOTIME3            1186
#define IDC_CHECK_VIDEOTIME4            1187
#define IDC_COMBO_STARTTIME1            1200
#define IDC_COMBO_ENDTIME1              1201
#define IDC_CHECK_STARTHIDEALARM        1205
#define IDC_COMBO_STARTTIME2            1206
#define IDC_BUTTON_HIDETIME             1206
#define IDC_COMBO_ENDTIME2              1207
#define IDC_COMBO_RESPONSE              1207
#define IDC_COMBO_STARTTIME3            1208
#define IDC_COMBO_SENSESECOND           1208
#define IDC_COMBO_ENDTIME3              1209
#define IDC_COMBO_STARTTIME4            1210
#define IDC_CHECK_STARMOVESENSE         1210
#define IDC_COMBO_ENDTIME4              1211
#define IDC_COMB_SERAILTYPE             1211
#define IDC_COMB_CHECKBIT               1215
#define IDC_CHECK_STARTIO               1225
#define IDC_COMBO_IOTYPE                1226
#define IDC_COMBO_SECONDS               1227
#define IDC_BUTTON_SETTIME              1228
#define IDC_LIST_WARNING                1229
#define IDC_BUTTON_PLAYBACK             1230
#define IDC_CHECK_STARTWARNINGUPLOAD    1231
#define IDC_EDIT_WARNINGDEVICEIP        1232
#define IDC_EDIT_WARNINGDEVICEPORT      1233
#define IDC_COMBO_WARNINGPROTOCOLTYPE   1234
#define IDC_EDIT_DEVICEID               1237
#define IDC_EDITSERVERID                1238
#define IDC_EDIT_DEVICEPASS             1239
#define IDC_EDITSERVERIP                1240
#define IDC_EDITSERVERPORT              1241
#define IDC_EDITSERVERMSG               1242
#define IDC_EDIT_CHANNELID              1243
#define IDC_BUTTON_WATCH                1245
#define IDC_LIST_VIDEOPLAYBACK          1246
#define IDC_BUTTON_SERACHVIDEO          1247
#define IDC_COMBOX_RECORDTYPE           1248
#define IDC_COMBOX_DEVICE               1249
#define IDC_DATETIMEPICKER_START        1250
#define IDC_DATETIMEPICKER_END          1251
#define IDC_COMBO_STARTHOUR             1252
#define IDC_COMBO_STARTMINUTE           1253
#define IDC_COMBO_STRATSECOND           1254
#define IDC_COMBO_ENDHOUR               1255
#define IDC_EIDT_ENDMINUTE              1256
#define IDC_COMBO_ENDSECOND             1257
#define IDC_PROGRESS1                   1259
#define IDC_BUTTON_DEVICE_CLOSE         1260
#define IDC_BUTTON_OUT_AGAIN            1261
#define IDC_BUTTON_MOREN                1262
#define IDC_BUTTON_PTZUP                1262
#define IDC_BUTTON_LIGHT_CHECK          1263
#define IDC_BUTTON_PTZLEFT              1263
#define IDC_BUTTON_DESTROYCHECK         1264
#define IDC_BUTTON_PTZDOWN              1264
#define IDC_BUTTON_PTZRIGHT             1265
#define IDC_BUTTOn_PTZAUTO              1266
#define IDC_COMBO_PTZJD                 1267
#define IDC_CHECK_STARTLIGHT            1268
#define IDC_CHECK_STARTBRUSH            1269
#define IDC_BUTTON_PTZSCANJIA           1270
#define IDC_CHECK_OSDOPPOSITE           1270
#define IDC_BUTTON_PTZSCANJIAN          1271
#define IDC_BUTTONTIMECOLOR             1271
#define IDC_BUTTON_TEXTCOLOR            1272
#define IDC_BUTTON_FORMATTING           1273
#define IDC_COMBO_FORMATCOUNT           1274
#define IDC_STATIC_SHOWLOSTSCREEN       1277
#define IDC_CHECK_START_LOST_WARNING    1278
#define IDC_BUTTON_SETLOSTTIME          1279
#define IDC_COMBO_LOSTTIME_INTERVAL     1280
#define IDC_CHECK_START_NET_DISK        1283
#define IDC_COMBOPROTOCOL               1284
#define IDC_EDIT_DISK_IP                1285
#define IDC_EDIT_DISK_PORT              1286
#define IDC_STATIC_STARTMACHINENAME     1287
#define IDC_EDIT_DISK_STARTMACHINENAME  1288
#define IDC_EDIT_DISK_NAME              1289
#define IDC_COMBO_RZTYPE                1292
#define IDC_EDIT_RZ_USER                1293
#define IDC_EDIT_RZ_PASS                1294
#define IDC_COMBO_LOGINRZTYPE           1296
#define IDC_EDITLOGIN_RZ_USER           1298
#define IDC_EDIT_LOGIN_RZ_PASS          1299
#define IDC_DATETIMEPICKER_DATE         1302
#define IDC_BUTTONGETTIME               1303
#define IDC_STATIC_SHOW_PLAYBACK_VIDEO  1304
#define IDC_BUTTON_DOWNLOAD             1305
#define IDC_BUTTON_STOPVIDEO            1306
#define IDC_BUTTON_MAINATTRIBUTE        1307
#define IDC_BUTTON_PLAYFILE             1308
#define IDC_BUTTON_PAUSE                1309
#define IDC_BUTTON_STOP                 1310
#define IDC_BUTTON_PLAYSLOW             1311
#define IDC_BUTTON_PLAYFAST             1312
#define IDC_CHECK_STARTAVD              1313
#define IDC_COMBO_DIAGNOSERULE          1314
#define IDC_CHECK_IFCHECK               1315
#define IDC_COMBO_SENSIVITY             1316
#define IDC_COMBO_WARNINGTIME           1317
#define IDC_CHECK_START1                1318
#define IDC_CHECK_START2                1319
#define IDC_CHECK_START3                1320
#define IDC_CHECK_START4                1321
#define IDC_DATASTART1                  1325
#define IDC_PROGRESS_DOWNLOAD           1326
#define IDC_DATASTART2                  1327
#define IDC_COMBO_LIMITNETSTATUS        1327
#define IDC_DATASTART3                  1328
#define IDC_COMBO_WIRELESSSATUS         1328
#define IDC_DATASTART4                  1329
#define IDC_COMBO_PPPOESTATUS           1329
#define IDC_DATAEND1                    1330
#define IDC_DATAEND2                    1331
#define IDC_DATAEND3                    1332
#define IDC_COMBO_WRTNINGTYPE           1332
#define IDC_DATAEND4                    1333
#define IDC_CHECK_SUPPORTCHANNEL        1333
#define IDC_CHECK_JOINTOUT              1334
#define IDC_CHECK_JOINTTAKEPITCURECHANNEL 1335
#define IDC_CHECK_JOINTCOICE            1336
#define IDC_CHECK_JOINTEMAIL            1337
#define IDC_EDIT_JOINTVIDEOTIME         1338
#define IDC_EDIT_JOINTVOICE             1339
#define IDC_EDIT_JOINTOUTTIME           1340
#define IDC_EDIT_JOINTTAKELEVER         1341
#define IDC_EDIT_JOINTPICTURECOUNT      1342
#define IDC_COMBO_WRTNINGTYPE2          1343
#define IDC_COMBO_CHOOSECHANNEL         1343
#define IDC_LIST_WIFI                   1345
#define IDC_BUTTON_RESET                1348
#define IDC_COMBO_DEVICE_STATE          1351
#define IDC_LIST_DISKSTATE              1352
#define IDC_COMBO_ALARM_IN              1353
#define IDC_COMBO_ALARM_OUT             1354
#define IDC_COMBO_LOCOLSHOW             1355
#define IDC_CHECK_STARTAUTOSTREAM       1355
#define IDC_COMBO_VOICECHANNEL          1356
#define IDC_COMBO_REPLACETYPE           1356
#define IDC_LIST_CHANNELSTATE           1358
#define IDC_EDIT_STREAM_HIGH            1358
#define IDC_EDIT_STREAM_LOW             1359
#define IDC_EDIT_STREAM_HIGH2           1360
#define IDC_EDIT_STREAM_LOW2            1361
#define IDC_EDIT_STREAM_HIGH3           1362
#define IDC_BUTTON_SERACH               1362
#define IDC_EDIT_STREAM_LOW3            1363
#define IDC_BUTTON_RECODE               1364
#define IDC_START_DATE                  1365
#define IDC_START_TIME                  1366
#define IDC_END_DATE                    1367
#define IDC_END_TIME                    1368
#define IDC_COMBO_RECODE_TYPE           1369
#define IDC_LIST_RECODE                 1370
#define IDC_EDIT_PLAYBACKIP             1371
#define IDC_COMBO_RECODE_TYPE2          1371
#define IDC_COMBO_RECODEDEVICE          1371
#define IDC_EDIT_RECODE_IP              1372
#define IDC_STATIC_COMPARE1             1373
#define IDC_STATIC_COMPARE2             1374
#define IDC_EDIT_DATABIT                1374
#define IDC_STATIC_COMPARE3             1375
#define IDC_EDIT_STOPBIT                1375
#define IDC_STATIC_COMPARE4             1376
#define IDC_EDIT_BAUDRATE               1376
#define IDC_EDIT_RATE                   1377
#define IDC_STATIC_COMPARE5             1378
#define IDC_EDIT_WIFIPASSWORD           1378
#define IDC_COMBO1                      1379
#define IDC_COMBO_WIFI_USETYPE          1379
#define IDC_COMBO_SENSITIVE             1379
#define IDC_COMBO_CABLENETWORK          1379
#define IDC_COMBO_SceneType             1379
#define IDC_COMBO_SHUTTER               1379
#define IDC_COMBO_VIDEOSENDMODE         1379
#define IDC_COMBO_SERVERAREA            1379
#define IDC_STATIC_COMPARE6             1380
#define IDC_COMBO_SETCOLOR              1380
#define IDC_COMBO_TargetLever           1380
#define IDC_COMBO_VIDEOSENDMODE2        1380
#define IDC_COMBO_MAT                   1380
#define IDC_COMBO2                      1380
#define IDC_STATIC_COMPARE7             1381
#define IDC_BUTTON_CLOSEALLVIDEO        1381
#define IDC_COMBO_MODEL                 1381
#define IDC_COMBO_RULELEVER             1381
#define IDC_COMBO3                      1381
#define IDC_STATIC_COMPARE8             1382
#define IDC_STATIC_JIBIAN               1383
#define IDC_EDIT_ADDRESS_STREAM         1383
#define IDC_STATIC_COMPARE9             1384
#define IDC_STATIC_WIDTHSTATE           1384
#define IDC_BUTTON1                     1385
#define IDC_BUTTON_CLEARWARNING         1385
#define IDC_BUTTON_TAKEAPICTURE         1385
#define IDC_BUTTON_FLASHDEVICE          1385
#define IDC_BUTTONJOINTACTION           1385
#define IDC_BUTTON_RECODESRC            1386
#define IDC_BUTTONCANCEL                1386
#define IDC_BUTTON_RECODESRC2           1387
#define IDC_BUTTON_DOWNSRC              1387
#define IDC_RADIO_AUTO_SWITCH           1390
#define IDC_RADIO_MANUAL_SWITCH         1391
#define IDC_RADIO_TIME_SWITCH           1392
#define IDC_CHECK_MANUAL                1393
#define IDC_BUTTON2                     1394
#define IDC_BUTTON_ALLFULLUP            1394
#define IDC_BUTTON_LISTEN               1394
#define IDC_BUTTON_SETTOP               1394
#define IDC_BUTTON_REFRESH              1394
#define IDC_DATETIMEPICKER1             1395
#define IDC_BUTTON_SETCURRENT           1395
#define IDC_DATETIMEPICKER2             1396
#define IDC_BUTTON_ELSE                 1396
#define IDC_DATETIMEPICKER3             1397
#define IDC_EDIT_TAKEAPICTURESRC        1397
#define IDC_DATETIMEPICKER4             1398
#define IDC_EDIT_RECODESRC              1398
#define IDC_DATETIMEPICKER5             1399
#define IDC_BUTTON3                     1399
#define IDC_EDIT_DOWNLOAD               1399
#define IDC_DATETIMEPICKER6             1400
#define IDC_STATIC_WIFISTATE            1400
#define IDC_DATETIMEPICKER7             1401
#define IDC_STATIC_SHOWTEXT             1401
#define IDC_DATETIMEPICKER8             1402
#define IDC_CHECK1                      1402
#define IDC_CHECK_StartNetWorkFault     1402
#define IDC_CHECK_StartPeaOsc           1402
#define IDC_CHECK_UPLOADFTP             1402
#define IDC_CHECK_ENABLEPICTURE         1402
#define IDC_CHECK_ENABLECPC             1402
#define IDC_CHECK_ENABLE                1402
#define IDC_CHECK_ENABLEZTE             1402
#define IDC_CHECK_StartWifi             1403
#define IDC_CHECK_AUTOSERVERPORT        1403
#define IDC_DATETIMEPICKER9             1403
#define IDC_CHECK7                      1403
#define IDC_CHECK_Start3G               1404
#define IDC_CHECK8                      1404
#define IDC_CHECK_STARTCABLE            1405
#define IDC_CHECK9                      1405
#define IDC_CHECK_StartAllCable         1406
#define IDC_BUTTON_DARW                 1407
#define IDC_ANIMATE1                    1408
#define IDC_STIME1                      1409
#define IDC_STIME2                      1410
#define IDC_STIME3                      1411
#define IDC_STIME4                      1412
#define IDC_ETIME1                      1413
#define IDC_ETIME2                      1414
#define IDC_ETIME3                      1415
#define IDC_ETIME4                      1416
#define IDC_StartTime1                  1417
#define IDC_StartTime2                  1418
#define IDC_StartTime3                  1419
#define IDC_CHECK10                     1419
#define IDC_StartTime4                  1420
#define IDC_COMBO_RULEID                1421
#define IDC_EDIT_RULENAME               1422
#define IDC_COMBO_RULEID2               1423
#define IDC_STATIC_RULEPARAM            1424
#define IDC_COMBO_Cross                 1425
#define IDC_CHECK_STARTRULE             1426
#define IDC_COMBO_ZJMODE                1427
#define IDC_CHECK_UPLOADALARM           1428
#define IDC_CHECK_SERVER                1429
#define IDC_CHECK_CLIENT                1430
#define IDC_EDIT_SPORT                  1432
#define IDC_STATIC_SHOWMODE             1433
#define IDC_PROGRESS_FORMAT             1434
#define IDC_STATIC_CONTROLDEV           1435
#define IDC_STATIC_SHOWRECODEVIDEO      1436
#define IDC_SLIDER_PLAYPROGRESS         1438
#define IDC_STATIC_GROPU_PROGRESS       1439
#define IDC_STATIC_SHOWPLAYTIME         1440
#define IDC_EDIT_DEVICEPUID             1441
#define IDC_EDIT_SERVERADDR             1442
#define IDC_EDIT_SERVERPORT             1443
#define IDC_EDIT_VIDEOPORT              1444
#define IDC_EDIT_AUDIOPORT              1445
#define IDC_EDIT_MESSAGEPORT            1446
#define IDC_EDIT_PLAYBACKPORT           1447
#define IDC_EDIT_MAXVIDEOCOUNT          1448
#define IDC_EDIT1                       1450
#define IDC_EDIT2                       1451
#define IDC_EDIT3                       1452
#define IDC_EDIT4                       1453
#define IDC_CHECK2                      1453
#define IDC_EDIT5                       1454
#define IDC_EDIT6                       1455
#define IDC_COMBO_LANGUAGE              1455
#define IDC_STATIC_SHOWMESSAGE          1456
#define IDC_STATIC_CHOOSECHANNEL        1457
#define IDC_COMBO_DETECTINTERVAL        1458
#define IDC_CHECK3                      1459
#define IDC_CHECK4                      1460
#define IDC_COMBO_UPLOAD                1460
#define IDC_CHECK5                      1461
#define IDC_CHECK_FULLDAYREC            1461
#define IDC_CHECK6                      1462
#define IDC_CHECK_ENABLE1               1462
#define IDC_START1                      1463
#define IDC_END1                        1464
#define IDC_COMBO_QUADR                 1464
#define IDC_CHECK_ENABLE2               1465
#define IDC_COMBO4                      1465
#define IDC_START2                      1466
#define IDC_EDIT_THETOP                 1466
#define IDC_END2                        1467
#define IDC_LIST_FLOOR                  1467
#define IDC_CHECK_ENABLE3               1468
#define IDC_START3                      1469
#define IDC_EDIT_LISTEDIT               1469
#define IDC_END3                        1470
#define IDC_EDIT_ADD                    1470
#define IDC_CHECK_ENABLE4               1471
#define IDC_BUTTON_SETLOOPADD           1471
#define IDC_START4                      1472
#define IDC_SLIDER1                     1472
#define IDC_END4                        1473
#define IDC_SLIDER2                     1473
#define IDC_SLIDER3                     1474
#define IDC_SLIDER4                     1475
#define IDC_SLIDER5                     1476
#define IDC_SLIDER6                     1477
#define IDC_SLIDER7                     1478
#define IDC_SLIDER8                     1479
#define IDC_STATIC_TEXT1                1480
#define IDC_STATIC_TEXT2                1481
#define IDC_BUTTON_COLOR                1481
#define IDC_STATIC_TEXT3                1482
#define IDC_STATIC_TEXT4                1483
#define IDC_EDIT_ID                     1483
#define IDC_STATIC_TEXT5                1484
#define IDC_COMBO_CHANNELNO             1484
#define IDC_STATIC_TEXT6                1486
#define IDC_LIST_CHANNELID              1486
#define IDC_EDIT_EDITCHANNEL            1487
#define IDC_STATIC_TEXT7                1488
#define IDC_STATIC_SPEED                1488
#define IDC_STATIC_TEXT8                1489
#define ID_MENU_32771                   32771
#define ID_MENU_FULLSCREEN              32772
#define ID_MENU_32773                   32773
#define ID_MENU_MAINSTREAM              32774
#define ID_MENU_32775                   32775
#define ID_MENU_SECONDSTREAM            32776
#define ID_MENU_32777                   32777
#define ID_MENU_THIRDSTREAM             32778
#define ID_MENU_32779                   32779
#define ID_MENU_CLOSE                   32780
#define menu                            32781
#define ID_MENU_32783                   32783
#define ID_MENU_DELETE                  32784
#define ID_MENU_32785                   32785
#define ID_MENU_ATTRIBUTE               32786
#define ID_MENU_32787                   32787
#define ID_MENU_DelList                 32788
#define IDM_                            32789
#define IDM_LOCALATTRIBUTE              32790
#define ID_Menu                         32791
#define ID_MENU_32793                   32793
#define ID_MENU_DEVICE_SNAP             32794

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        220
#define _APS_NEXT_COMMAND_VALUE         32795
#define _APS_NEXT_CONTROL_VALUE         1489
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
