//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by IVS_VDemo.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_IVS_VDemo_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define IDD_DLG_PROFILE                 130
#define IDD_DLG_TASK                    131
#define IDD_DLG_PROJECT                 132
#define IDD_DLG_GLOBAL                  133
#define IDD_DLG_LISTEN                  134
#define IDD_DLG_QUERY                   135
#define IDD_DLG_DEVICE                  136
#define IDD_DLG_LOGIN                   137
#define IDD_DLG_PROFILE_INFO1           138
#define IDD_DLG_ADDDEVICE               139
#define IDB_DEVICETREEIMAGE             140
#define IDC_BTN_PROFILE_CFG             1000
#define IDC_BTN_TASK_CFG                1001
#define IDC_BTN_PROJECT_CFG             1002
#define IDC_BTN_LISTEN                  1004
#define IDC_BTN_QUERY                   1005
#define IDC_TREE_PROFILE                1007
#define IDC_EDIT_IP                     1008
#define IDC_EDIT_PORT                   1009
#define IDC_EDIT_USERNAME               1010
#define IDC_EDIT_PASSWORD               1011
#define IDC_BTN_LOGIN                   1012
#define IDC_BTN_ADD                     1013
#define IDC_BTN_DELETE                  1014
#define IDC_BTN_SET                     1016
#define IDC_EDIT_PROFILE_NAME           1019
#define IDC_CHECK_ENABLE                1020
#define IDC_EDIT_PROFILE_MINDURATION    1021
#define IDC_EDIT_PROFILE_THRESHOLD1     1022
#define IDC_EDIT_PROFILE_THRESHOLD2     1023
#define IDC_CONFIG_AREA                 1024
#define IDC_EDIT_PROFILE_THRESHOLD1_UP  1024
#define IDC_EDIT_PROFILE_THRESHOLD2_UP  1025
#define IDC_STATIC_2UP                  1026
#define IDC_STATIC_2                    1027
#define IDC_STATIC_1UP                  1028
#define IDC_STATIC_1                    1029
#define IDC_STATIC_MINDURATION          1030
#define IDC_STATIC_NAME                 1031
#define IDC_BTN_GET                     1032
#define IDC_CHECK_UVD                   1035
#define IDC_EDIT1                       1036
#define IDC_TREE_DEVICE                 1037
#define IDC_COMBO_DURATION              1039
#define IDC_BTN_ADD_TASK                1040
#define IDC_COMBO_TASKLIST              1041
#define IDC_EDIT_TASKNAME               1042
#define IDC_LIST_SUBTASK                1043
#define IDC_COMBO_PROFILENAME           1044
#define IDC_BTN_GET_TASK                1045
#define IDC_BTN_SET_TASK                1046
#define IDC_BTN_MODIFY_TASK             1047
#define IDC_BTN_DELETE_TASK             1048
#define IDC_COMBO_PROJECT               1049
#define IDC_BTN_DEL                     1051
#define IDC_EDIT_PROJECT_NAME           1052
#define IDC_BTN_MODIFY                  1053
#define IDC_BTN_DEL_TASK                1054
#define IDC_COMBO_TASK                  1057
#define IDC_LIST_PROJECT_INFO           1058
#define IDC_DATETIMEPICKER_START        1059
#define IDC_DATETIMEPICKER_END          1060
#define IDC_LIST_RESULT                 1061
#define IDC_DATETIMEPICKER_START_DATE   1063
#define IDC_DATETIMEPICKER_END_DATE     1064
#define IDC_DATETIMEPICKER_START_TIME   1065
#define IDC_DATETIMEPICKER_END_TIME     1066
#define IDC_RADIO_ALL_DEVICES           1067
#define IDC_RADIO_ONE_DEVICE            1068
#define IDC_EDIT_PAGEINDEX              1070
#define IDC_EDIT_PAGESUM                1071
#define IDC_BTN_PREPAGE                 1072
#define IDC_BTN_NEXTPAGE                1073
#define IDC_BTN_ENDPAGE                 1074
#define IDC_BTN_FIRSTPAGE               1075
#define IDC_EDIT_GOPAGE                 1076
#define IDC_BTN_GOPAGE                  1077
#define IDC_IPADDRESS1                  1078
#define IDC_EDIT_WAITTIME               1079
#define IDC_BTN_SAVEPAGE                1086
#define IDC_BTN_QUIT                    1087
#define IDC_STATIC_MAIN                 1089
#define IDC_STATIC_DEVLIST              1090
#define IDC_STATIC_TEST                 1091
#define IDC_BTN_STOP_QUERY              1092
#define IDC_BTN_DEL_ITEM                1093
#define IDC_BTN_CLEAR_ITEM              1094
#define IDC_STATIC_RESULT               1097
#define IDC_BTN_START_LISTEN            1098
#define IDC_BTN_STOP_LISTEN             1099
#define IDC_RADIO_LISTEN_ALL_DEVICES    1105
#define IDC_LISTEN_IPADDRESS            1106
#define IDC_RADIO_LISTEN_ONE_DEVICE     1107
#define IDC_LISTEN_LIST_RESULT          1108
#define IDC_LISTEN_BTN_FIRSTPAGE        1109
#define IDC_LISTEN_BTN_PREPAGE          1110
#define IDC_LISTEN_EDIT_PAGEINDEX       1111
#define IDC_LISTEN_EDIT_PAGESUM         1112
#define IDC_LISTEN_BTN_NEXTPAGE         1113
#define IDC_LISTEN_BTN_ENDPAGE          1114
#define IDC_LISTEN_EDIT_GOPAGE          1115
#define IDC_LISTEN_BTN_GOPAGE           1116
#define IDC_LISTEN_EDIT_WAITTIME        1118
#define IDC_COLLECTIVITY_STATE          1119
#define IDC_FAILED_CAUSE                1120
#define IDC_RESULT_TYPE                 1121
#define ID_MPROFILE                     32771
#define ID_MTASK                        32772
#define ID_MPROJECT                     32773
#define ID_MGLOBAL                      32774
#define ID_MLISTEN                      32775
#define ID_MFIND                        32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1122
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
