//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DemoIVSb.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DEMOIVSB_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDR_TOOLBAR                     129
#define IDR_MENU                        131
#define IDD_LOGIN                       133
#define IDD_SWITCH                      134
#define IDD_CONFIG                      135
#define IDD_CONFIG_GLOBAL               136
#define IDD_CONFIG_MODULE               137
#define IDD_CONFIG_RULES                138
#define IDD_PREVIEW                     139
#define IDD_ALARM                       140
#define IDD_SUBDLG_RULE01_CROSSFENCE    141
#define IDD_SUBDLG_RULE02_CROSSLINE     142
#define IDD_SUBDLG_RULE03_CROSSREGION   143
#define IDD_SUBDLG_RULE04_MOVE          144
#define IDD_SUBDLG_RULE05_LEFT          145
#define IDD_SUBDLG_RULE06_PARKING       146
#define IDD_SUBDLG_RULE07_PRESERV       147
#define IDD_SUBDLG_RULE08_RETROGRA      148
#define IDD_SUBDLG_RULE09_STAY          149
#define IDD_SUBDLG_RULE10_TAKENAWAY     150
#define IDD_SUBDLG_RULE11_VIDEOABNORMAL 151
#define IDD_SUBDLG_RULE12_WANDER        152
#define IDD_SUBDLG_LOGO                 153
#define IDD_TARGET_FILTER               154
#define IDC_LOGIN_IPADDR_IP             1001
#define IDC_LOGIN_EDT_PORTNUM           1002
#define IDC_LOGIN_EDT_USERNAME          1003
#define IDC_LOGIN_EDT_PSW               1004
#define IDC_MAIN_CHK_SWITCH             1010
#define IDC_MAIN_BTN_PREVIEW            1011
#define IDC_MAIN_BTN_CONFIG             1012
#define IDC_MAIN_BTN_ALARM              1013
#define IDC_MAIN_BTN_LOGOUT             1014
#define IDC_SWITCH_TREE_CHN             1020
#define IDC_SWITCH_TREE_RULE            1021
#define IDC_SWITCH_BTN_CHNSELALL        1022
#define IDC_SWITCH_BTN_CHNCOUNTERSEL    1023
#define IDC_SWITCH_BTN_RULESELALL       1024
#define IDC_SWITCH_BTN_RULECOUNTERSEL   1025
#define IDC_PREVIEW_CMB_CHANNEL         1030
#define IDC_PREVIEW_LIST_ALARM          1031
#define IDC_PREVIEW_STATIC_PREVIEW      1032
#define IDC_ALARM_LIST_ALARMINFO        1040
#define IDC_ALARM_DTP_STARTDATE         1041
#define IDC_ALARM_DTP_ENDDATE           1042
#define IDC_ALARM_DTP_STARTTIME         1043
#define IDC_ALARM_DTP_ENDTIME           1044
#define IDC_ALARM_STATIC_VIEW           1045
#define IDC_ALARM_TREE_RULESEL          1046
#define IDC_ALARM_CMB_CHANNEL           1047
#define IDC_CONFIG_TAB                  1050
#define IDC_CFGRULE_BTN_ADDRULE         1060
#define IDC_CFGRULE_BTN_DELRULE         1061
#define IDC_CFGRULE_STATIC_PREVIEW      1062
#define IDC_CFGRULE_BTN_SET             1063
#define IDC_CFGRULE_BTN_GET             1064
#define IDC_CFGRULE_BTN_REDRAW          1065
#define IDC_CFGRULE_EDT_CHANNELNAME     1066
#define IDC_CFGRULE_TREE_RULELIST       1067
#define IDC_CFGRULE_EDT_RULENAME        1068
#define IDC_CFGRULE_CMB_RULETYPE        1069
#define IDC_CFGMOD_BTN_ADDMOD           1077
#define IDC_CFGMOD_BTN_DELMOD           1078
#define IDC_CFGMOD_CHK_ENCAP            1079
#define IDC_CFGMOD_TREE_TRACKREGION     1080
#define IDC_CFGMOD_BTN_ADDDETEC         1081
#define IDC_CFGMOD_BTN_ADDEXCLUD        1082
#define IDC_CFGMOD_BTN_REDRAW           1083
#define IDC_CFGMOD_BTN_DELREGION        1084
#define IDC_CFGMOD_CMB_OBJTYPE          1085
#define IDC_CFGMOD_CMB_BANLANCE         1086
#define IDC_CFGMOD_SLID_SENSI           1087
#define IDC_CFGMOD_BTN_FILTER           1088
#define IDC_CFGMOD_CHK_ENFILTER         1089
#define IDC_CFGMOD_BTN_SET              1090
#define IDC_CFGMOD_BTN_GET              1091
#define IDC_CFGMOD_TREE_MODLIST         1092
#define IDC_CFGMOD_EDT_CHANNELNAME      1093
#define IDC_CFGMOD_STATIC_PREVIEW       1094
#define IDC_CFGGLO_EDT_CHANNELNAME      1095
#define IDC_CFGGLO_CMB_SCENE            1096
#define IDC_CFGGLO_BTN_SET              1097
#define IDC_CFGGLO_BTN_GET              1098
#define IDC_CFGGLO_TREE_REGION          1099
#define IDC_CFGGLO_RADIO_VRULER         1100
#define IDC_CFGGLO_RADIO_HRULER         1101
#define IDC_CFGGLO_EDT_REALLEN          1102
#define IDC_CFGGLO_BTN_ADDAERA          1103
#define IDC_CFGGLO_BTN_DELAREA          1104
#define IDC_CFGGLO_BTN_RESET            1105
#define IDC_CFGGLO_STATIC_PREVIEW       1106
#define IDC_CFGGLO_BTN_ADDRULER         1107
#define IDC_CFGGLO_BTN_DELRULER         1108
#define IDC_CFGGLO_BTN_REDRAW           1109
#define IDC_RULE1_TREE_OBJTYPE          3100
#define IDC_RULE1_CMB_DIRECTION         3101
#define IDC_RULE1_RADIO_GFILTER         3113
#define IDC_RULE1_RADIO_CFILTER         3114
#define IDC_RULE2_TREE_OBJTYPE          3202
#define IDC_RULE2_CMB_DIRECTION         3203
#define IDC_RULE2_RADIO_GFILTER         3204
#define IDC_RULE2_RADIO_CFILTER         3205
#define IDC_RULE2_CMB_TRIGGERPOS        3206
#define IDC_RULE3_EDT_MINTARG           3300
#define IDC_RULE3_CMB_DIRECTION         3301
#define IDC_RULE3_EDT_MAXTARG           3302
#define IDC_RULE3_TREE_ACTIONTYPE       3303
#define IDC_RULE3_TREE_OBJTYPE          3304
#define IDC_RULE3_EDT_MINDUR            3305
#define IDC_RULE3_EDT_REPORTINTERVAL    3306
#define IDC_RULE3_RADIO_GFILTER         3307
#define IDC_RULE3_RADIO_CFILTER         3308
#define IDC_RULE4_TREE_OBJTYPE          3406
#define IDC_RULE4_TREE_DETECTTYPE       3407
#define IDC_RULE4_SLID_SENSI            3408
#define IDC_RULE4_EDT_MINDUR            3409
#define IDC_RULE4_RADIO_GFILTER         3410
#define IDC_RULE4_RADIO_CFILTER         3411
#define IDC_RULE5_CMB_TRIGGERPOS        3515
#define IDC_RULE5_EDT_MINDUR            3516
#define IDC_RULE5_RADIO_GFILTER         3517
#define IDC_RULE5_RADIO_CFILTER         3518
#define IDC_RULE6_CMB_TRIGGERPOS        3600
#define IDC_RULE6_EDT_MINDUR            3601
#define IDC_RULE6_RADIO_GFILTER         3602
#define IDC_RULE6_RADIO_CFILTER         3603
#define IDC_RULE7_EDT_MINDUR            3700
#define IDC_RULE8_TREE_OBJTYPE          3800
#define IDC_RULE8_BTN_DRAWDIRECTION     3801
#define IDC_RULE8_CMB_TRIGGERPOS        3802
#define IDC_RULE8_SLID_SENSI            3803
#define IDC_RULE8_RADIO_GFILTER         3804
#define IDC_RULE8_RADIO_CFILTER         3805
#define IDC_RULE9_TREE_OBJTYPE          3900
#define IDC_RULE9_EDT_MINDUR            3901
#define IDC_RULE9_EDT_REPORTINTERVAL    3902
#define IDC_RULE9_RADIO_GFILTER         3903
#define IDC_RULE9_RADIO_CFILTER         3904
#define IDC_RULE10_CMB_TRIGGERPOS       4000
#define IDC_RULE10_EDT_MINDUR           4001
#define IDC_RULE10_RADIO_GFILTER        4002
#define IDC_RULE10_RADIO_CFILTER        4003
#define IDC_RULE11_TREE_ACTIONTYPE      4100
#define IDC_RULE11_TREE_DETECTTYPE      4100
#define IDC_RULE11_EDT_MINDUR           4101
#define IDC_RULE11_SLID_SENSI           4102
#define IDC_RULE12_TREE_OBJTYPE         4200
#define IDC_RULE12_EDT_MINDUR           4201
#define IDC_RULE12_EDT_REPORTINTERVAL   4202
#define IDC_RULE12_RADIO_GFILTER        4203
#define IDC_RULE12_RADIO_CFILTER        4204
#define IDC_PROGRESS                    4205
#define IDC_SWITCH_STATIC_CHN           4206
#define IDC_SWITCH_STATIC_RULE          4207
#define IDC_COMBO_FILTER_PATTERN        4211
#define IDC_STATIC_VEDIO_VIEW           4227
#define IDC_CHECK_RECTANGLE             4228
#define IDC_COMBO_FILTER_TYPE           4229
#define IDC_BTN_FILTER_OK               4232
#define IDC_BTN_FILTER_CANCEL           4233

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        155
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         4234
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
