//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by NVDSDKDemo.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_NVDSDKDEMO_DIALOG           102
#define IDD_DLG_DECODEPOLICY            103
#define IDR_MAINFRAME                   128
#define IDD_DLG_ADD_DECODER             129
#define IDD_DLG_ADD_DEVICE              130
#define IDD_DLG_AUDIOTALK               131
#define IDD_DLG_SEARCH_TV               135
#define IDD_PANNEL_DECODER              137
#define IDD_PANNEL_ENCODER              138
#define IDD_DLG_TOUR                    143
#define IDD_DLG_DEV_FILE                144
#define IDD_DLG_DEV_TIME                145
#define IDD_DLG_PLAYBACK_PROCESS        146
#define IDD_DLG_CHANNEL_STATE           148
#define IDD_DLG_VIDEOOUT                149
#define IDD_DIALOG_TV_ADJUST            150
#define IDD_DLA_TOUR_CFG                151
#define IDD_DIALOG_ENCODER_INFO         152
#define IDC_SCREEN_WINDOW               1000
#define IDC_BTN_ADD_DECODER             1001
#define IDC_EDIT_DEV_NAME               1002
#define IDC_BTN_AUDIOTALK               1002
#define IDC_TREE_DECODER                1003
#define IDC_EDIT_DEV_IP                 1003
#define IDC_BTN_DEC_DECODER             1004
#define IDC_EDIT_DEV_PORT               1004
#define IDC_BTN_DEL_DECODER             1004
#define IDC_EDIT_DEV_USER               1005
#define IDC_TREE_ENCODER                1005
#define IDC_BTN_ADD_ENCODER             1006
#define IDC_EDIT_DEV_PWD                1006
#define IDC_EDIT_DEC_IP                 1007
#define IDC_BTN_DEL_ENCODER             1007
#define IDC_EDIT_DEC_PORT               1008
#define IDC_BTN_CLOSE_VIDEO             1008
#define IDC_EDIT_DEC_USER               1009
#define IDC_BTN_SEARCH                  1009
#define IDC_BTN_PLAYBACK_FILE           1009
#define IDC_EDIT_DEC_PWD                1010
#define IDC_BTN_TOUR                    1010
#define IDC_BTN_PLAYBACK_TIME           1010
#define IDC_EDIT_DEC_NAME               1011
#define IDC_STATIC_ENC_TYPE             1012
#define IDC_COMBO_ENC_TYPE              1014
#define IDC_BTN_STARTTALK               1015
#define IDC_BTN_STOPTALK                1016
#define IDC_STATIC_TV                   1032
#define IDC_COMBO_TVID                  1034
#define IDC_LIST_TVID                   1035
#define IDC_BTN_SEARCH_OK               1036
#define IDC_STATIC_TV_ID                1082
#define IDC_STATIC_DISMODE              1084
#define IDC_COMBO_DISMODE               1085
#define IDC_STATIC_CHANNEL              1086
#define IDC_COMBO_                      1087
#define IDC_SPLIT_INFO1                 1095
#define IDC_SPLIT_INFO2                 1096
#define IDC_SPLIT_INFO3                 1097
#define IDC_SPLIT_INFO4                 1098
#define IDC_SPLIT_INFO5                 1099
#define IDC_SPLIT_INFO6                 1100
#define IDC_SPLIT_INFO7                 1101
#define IDC_SPLIT_INFO8                 1102
#define IDC_SPLIT_INFO9                 1103
#define IDC_SPLIT_INFO10                1104
#define IDC_SPLIT_INFO11                1105
#define IDC_SPLIT_INFO12                1106
#define IDC_SPLIT_INFO13                1107
#define IDC_SPLIT_INFO14                1108
#define IDC_SPLIT_INFO15                1109
#define IDC_SPLIT_INFO16                1110
#define IDC_STATIC_TIME                 1121
#define IDC_BTN_ADD_COMBIN              1122
#define IDC_BTN_DEL_COMBIN              1123
#define IDC_BTN_DEL_ALLCOMBIN           1124
#define IDC_BTN_TOUR_OK                 1125
#define IDC_BTN_TOUR_CANCEL             1127
#define IDC_BTN_QUERY_COMBIN            1128
#define IDC_TREE_COMBIN                 1129
#define IDC_EDIT_TOURTIME               1132
#define IDC_BUT_CHANGEENABLE            1136
#define IDC_COMBO_CHANNEL               1137
#define IDC_COMBO_RECORD_TYPE           1138
#define IDC_DATE_START                  1139
#define IDC_TIME_START                  1140
#define IDC_DATE_END                    1141
#define IDC_TIME_END                    1142
#define IDC_LIST_RECORD_INFO            1144
#define IDC_BUTTON_QUERY                1145
#define IDC_BTN_CLOSE                   1151
#define IDC_SLIDER_PROCESS              1153
#define IDC_BTN_WORK                    1154
#define IDC_BTN_PLAY                    1155
#define IDC_BTN_STOP                    1156
#define IDC_BNT_CHANNEL_STATE           1156
#define IDC_BNT_VIDEOOUT                1157
#define IDC_COMBO_STANDER               1158
#define IDC_COMBO_RESOLUTION            1159
#define IDC_BNT_TV_ADJUST               1160
#define IDC_SLIDER_TOP                  1161
#define IDC_SLIDER_BOTTON               1162
#define IDC_SLIDER_LEFT                 1163
#define IDC_SLIDER_RIGHT                1164
#define IDC_COMBO1                      1165
#define IDC_INT_TOP                     1166
#define IDC_INT_BOTTON                  1167
#define IDC_INT_LEFT                    1168
#define IDC_INT_RIGHT                   1169
#define IDC_BUTTON_SNAP                 1170
#define IDC_COMBO_STREAMTYPE            1171
#define IDC_EDIT_IP                     1173
#define IDC_EDIT_PORT                   1174
#define IDC_EDIT_USER                   1175
#define IDC_EDIT_PWD                    1176
#define IDC_EDIT_INTERVAL               1177
#define IDC_EDIT_RTSPPORT               1178
#define IDC_COMBO_TYPE                  1179
#define IDC_STATIC_TOURNUM              1180
#define IDC_STATIC_IP                   1181
#define IDC_STATIC_PORT                 1182
#define IDC_STATIC_CHN                  1183
#define IDC_STATIC_TYPE                 1184
#define IDC_STATIC_USER                 1185
#define IDC_STATIC_PWD                  1186
#define IDC_STATIC_INTERVAL             1187
#define IDC_COMBO_DECODERCHANNEL        1188
#define ID_QUERY                        1189
#define ID_SAVE                         1190
#define IDC_BNT_TOUR_CFG                1191
#define IDC_STATIC_HTPPPORT             1191
#define IDC_STATIC_RTSPPORT             1192
#define IDC_ADD                         1193
#define IDC_DELETE                      1194
#define IDC_LIST_TOUR_INFO              1195
#define IDC_DELETE_ALL                  1196
#define IDC_RADIO1                      1197
#define IDC_RADIO2                      1198
#define IDC_RADIO3                      1199
#define IDC_CONTROL                     1200
#define IDC_EDIT_HTTPPORT               1201
#define IDC_STATIC_ManuFactory          1202
#define IDC_COMBO_MANUFACTORY           1203
#define IDC_RADIO4                      1204
#define IDC_BUTTON_ENCODER_INFO         1205
#define IDC_BUTTON_GET                  1206
#define IDC_BUTTON_SET                  1207
#define IDC_COMBO_ENCODER_NUM           1208
#define IDC_CHECK_ENABLE                1209
#define IDC_EDIT_USERNAME               1213
#define IDC_EDIT_PASSWORD               1214
#define IDC_EDIT_CHANNEL                1215
#define IDC_COMBO_STREAM_TYPE           1216
#define IDC_COMBO_CONNECT_TYPE          1217
#define IDC_BUTTON_DECODEPOLICY         1217
#define IDC_COMBO_WORK_MODE             1218
#define IDC_EDIT_LISTEN_PORT            1219
#define IDC_COMBO_PROTOCOL_TYPE         1220
#define IDC_EDIT_DEVICE_NAME            1221
#define IDC_COMBO_SNAP_MODE             1222
#define IDC_BUTTON_REFRESH              1222
#define IDC_COMBO_FACTORY               1223
#define IDC_COMBO_DEVICE_TYPE           1224
#define IDC_STATIC_DECODERCHANNEl       1224
#define IDC_STATIC_REGION               1225
#define IDC_BUTTON_SAVE                 1226
#define IDC_EDIT_TIME                   1227
#define IDC_CHECK_1                     2095
#define IDC_CHECK_2                     2096
#define IDC_CHECK_3                     2097
#define IDC_CHECK_4                     2098
#define IDC_CHECK_5                     2099
#define IDC_CHECK_6                     2100
#define IDC_CHECK_7                     2101
#define IDC_CHECK_8                     2102
#define IDC_CHECK_9                     2103
#define IDC_CHECK_10                    2104
#define IDC_CHECK_11                    2105
#define IDC_CHECK_12                    2106
#define IDC_CHECK_13                    2107
#define IDC_CHECK_14                    2108
#define IDC_CHECK_15                    2109
#define IDC_CHECK_16                    2110

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        153
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1225
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
